# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='leaving_date',
            new_name='departure_date',
        ),
    ]
