# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20160402_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
