# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_auto_20160406_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='quit_counts',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
