# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 01:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_auto_20160406_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blocked_until',
            field=models.DateField(default=datetime.datetime(2016, 4, 7, 1, 49, 48, 646905, tzinfo=utc)),
        ),
    ]
