# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 02:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_userprofile_blocked_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_blocked',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blocked_until',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 7, 2, 3, 31, 40181, tzinfo=utc)),
        ),
    ]
