# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_auto_20160406_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blocked_until',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
