# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0016_auto_20160406_2220'),
        ('public', '0013_trip_is_completed'),
    ]

    operations = [
    ]
