# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0017_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
